INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (1, '26/09/2023', 'giovanni@gmail.com', 'giovanni', 'rossi')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (2, '26/09/2023', 'marco@gmail.com', 'marco', 'luciani')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (3, '26/09/2023', 'riccardo@gmail.com', 'riccardo', 'battisti')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (4, '26/09/2023', 'alfonso@gmail.com', 'alfonso', 'mengoni')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (5, '26/09/2023', 'cosimo@gmail.com', 'cosimo', 'picozzi')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (6, '26/09/2023', 'valerio@gmail.com', 'valerio', 'marino')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (7, '26/09/2023', 'anna@gmail.com', 'anna', 'ursino')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (8, '26/09/2023', 'mirko@gmail.com', 'mirko', 'fava')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (9, '26/09/2023', 'luca@gmail.com', 'luca', 'giusti')
INSERT INTO CLIENT (id, birth, email, name, surname) VALUES (10, '26/09/2023', 'ciro@gmail.com', 'ciro', 'immobile')
INSERT INTO EDITOR (id, name) VALUES (1, 'Mondadori')
INSERT INTO EDITOR (id, name) VALUES (2, 'Feltrinelli')
INSERT INTO EDITOR (id, name) VALUES (3, 'Alephi')
INSERT INTO EDITOR (id, name) VALUES (4, 'Hoepli')
INSERT INTO AUTHOR (id, birth, name, surname) VALUES (1, '26/09/2023', 'pasquale', 'bravi')
INSERT INTO AUTHOR (id, birth, name, surname) VALUES (2, '26/09/2023', 'salvatore', 'bianchi')
INSERT INTO AUTHOR (id, birth, name, surname) VALUES (3, '26/09/2023', 'giuseppe', 'picchi')
INSERT INTO AUTHOR (id, birth, name, surname) VALUES (4, '26/09/2023', 'gennaro', 'pastore')
INSERT INTO BOOK (is_available, author_id, client_id, editor_id, price, isbn, title) VALUES (false, 1, 1, 1, 79.40, 1, 'Just for fun!')
INSERT INTO BOOK (is_available, author_id, client_id, editor_id, price, isbn, title) VALUES (false, 2, 2, 2, 19.00, 2, 'Il nuovo java')
INSERT INTO BOOK (is_available, author_id, client_id, editor_id, price, isbn, title) VALUES (false, 3, 3, 3, 31.90, 3, 'Libro di letteratura')
